# Generated by Django 4.1.5 on 2023-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile/images'),
        ),
    ]
